spring.application.name=name-insight-api
# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:nameinsightdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=wendy-wej
spring.datasource.password=

# Let Hibernate auto-create tables from your entities
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 web console (so you can inspect your DB in a browser)
spring.h2.console.enabled=true